### ISSUE TITLE
Câu hỏi trong seminar

### ISSUE THREAD

**Issue by ductnn** [ductnn/Kubernetes-tu#4]
- [x] Container Orchestration là gì?
- [x] Self-healing
- [x] Control Plane là gì ? Control plane bao gồm những thành phần nào ? Ngoài control plane thì còn plane khác không ?
- [x] Những dữ liệu lưu trong etcd là dữ liệu gì ? Tại sao phải dùng etcd ?
- [x] Desired state trong kubernetes ? 
- [ ] Giải thích ý nghĩa "affinity and anti-affinity specifications, data locality, inter-workload interference, and deadlines".
- [x] PodSpecs là gì ?
- [x] Kube-proxy quản lý toàn bộ traffic là đúng hay sai ? 
- [x] Services expose cái gì ?
- [x] iptables là do ai tạo ra ? 
- [x] Selector là gì ? 
- [x] LoadBalancer là những phần mềm gì ?
- [x] Mô hình em để trong slide là Deployment Arch, hay Logical Arch
- [x] Anh Công có bảo, các thành phần như trong mô hình như thế là chưa update, tham khảo chưa đúng nguồn --> update lại --> hình đúng phải là hình như thế nào?
- [x] kubelet tương tác đến pods hay tương tác đến tận container? Tại sao?
- [x] Có gọi trực tiếp vào API server mà không phải thông qua Kubectl được không? Nếu có thì làm thế nào?
- [x] Có thể triển khai workload trên master node không? Tại sao?
- [x] User-space, IPVS là gì? (trả lời câu hỏi WHAT thôi, không yêu cầu trả lời sâu hơn)
- [x] Trong slide 14, Client nghĩa là gì, đại diện cho cái gì?
- [x] Docker có phải là container runtime không?
- [ ] Docker và containerd có gì khác nhau?

**Comment by tovin07** [comment]
Còn thiếu mấy câu:

- Mô hình em để trong slide là Deployment Arch, hay Logical Arch
- Anh Công có bảo, các thành phần như trong mô hình như thế là chưa update, tham khảo chưa đúng nguồn --> update lại --> hình đúng phải là hình như thế nào?
- kubelet tương tác đến pods hay tương tác đến tận container? Tại sao?
- Có gọi trực tiếp vào API server mà không phải thông qua Kubectl được không? Nếu có thì làm thế nào?
- Có thể triển khai workload trên master node không? Tại sao?
- User-space, IPVS là gì? (trả lời câu hỏi WHAT thôi, không yêu cầu trả lời sâu hơn)
- Trong slide 14, `Client` nghĩa là gì, đại diện cho cái gì?
- Docker có phải là container runtime không?
- Docker và containerd có gì khác nhau?
